### ISSUE TITLE
Problème ajout de variable dans les modules

### ISSUE THREAD

**Issue by Adopo** [benkuper/Chataigne#19]
Hello Ben. It's been a long time I didn't had variable in my different module so I don't know if this problem is with the new release or if it come long time ago.
When I want to add a variable on my module LGML with auto-add, is different of the old variable. The variable is with a minimum and maximum at 0, the variable in the inspector of the module is little bit transparent and when I put a condition on it, even I change the maximum and minimum, the condition don't care about my variable.

I join you the files of my project. To experiment the bug, you just have to had a variable mute from LGML with auto-add. I have added .txt on files because the extentions of LGML et Chataigne can't be uploaded.

[adopo-center-openstage-1.2.15 copie.noisette.txt](https://github.com/benkuper/Chataigne/files/1751655/adopo-center-openstage-1.2.15.copie.noisette.txt)
[Black Looper 6 copie.lgml.txt](https://github.com/benkuper/Chataigne/files/1751657/Black.Looper.6.copie.lgml.txt)

**Comment by benkuper** [comment]
Ok i checked it and i see, this is actually the right behavior but i understand it represent a slight change of methodology on your side.
The modules values are not supposed to be changeable for the user. These are exposed values from outside Chataigne.
For instance you shouldn't have any expression defining the value of a module because it's supposed to be set from the module itself.
That's why in the new versions, the values are read-only (you can't modify them).
I need to fix some issues with  the range adapt but if you want those values to adapt to what they receive and not lock their values to the first one they got, just check "auto range" below "auto add" and the values will always adapt their range if values received are outside their initial range.

As for setting up your own values, there is now Custom Variables support in the 1.3.0b version !
Please check it out and tell me if that works for you.
