### ISSUE TITLE
OSCQuery LISTEN extension falsly assumed

### ISSUE THREAD

**Issue by joreg** [benkuper/Chataigne#192]
**Environment**
 - OS: Windows 11
 
**Describe the bug**
i have an oscquery server that does not support the LISTEN extension and its hostinfo also doesn't report it but when connecting, the logger shows: OSCQuery	Server has LISTEN extension, setting up websocket

**To Reproduce**
1. run this [DataSender example](https://github.com/vrchat-community/vrc-oscquery-lib/tree/main/Examples/DataSender)
2. connect to the given port from chataigne
3. see the wrong log message in the Logger

**Expected behavior**
the logger should tell me that the server does not support the LISTEN attribute. i would then expect it to fall back to using the VALUE attribute for querying the value periodically.

**Comment by benkuper** [comment]
Thank you for the feedback, I'll fix it when I get time.
However, I would not implement an automatic recurrent polling  through http if the server doesn't have LISTEN support. HTTP polling is just slow, and polling it at a decent rate so it feels like actual feedback would not feel good for performance. especially since the polling would obviously also happen when the value has not changed, which is most of the time for most cases.
I could add though an "update" trigger in containers for that.

**Comment by benkuper** [comment]
It seems that it was only a Log bug, it was not trying to connect to websocket. but thanks for the feedback, it will be fixed in next commit :)
