### ISSUE TITLE
KinectV2 not compiled into Mac 1.9.19 & Source Module dropdown not immediately present in Router

### ISSUE THREAD

**Issue by B0bMartin** [benkuper/Chataigne#249]
**Environment**
 - OS: [e.g. Windows 10, MacOS 10.14]
 - Version [e.g. 1.7.2]

**Describe the bug**
Hi Ben, I'm very new to Chataigne having being introduced to it by a technician Toulouse Natural History Museum (who I think you have met). I'm running through the English tutorial and copying what you do. I noticed that an error is presented as KinectV2 has not been compiled into the Mac V1.9.19 version.

<img width="554" alt="Screenshot 2024-09-24 at 11 00 15" src="https://github.com/user-attachments/assets/4f539c10-8c91-48b3-b4b2-99317e08e0aa">

The second issue I discovered is that the Source Module dropdown did not appear initially in Router. This happened the first time I tried adding modules to the Router. It took the opening of a second Router to make the dropdown to appear. 

<img width="667" alt="Screenshot 2024-09-24 at 11 08 01" src="https://github.com/user-attachments/assets/6a15cb40-d754-453b-8071-386c2d062dd6">

**To Reproduce**
1. Router dropdown - I have tried to repeat this and it is now reliable, choosing the same modules each time. Quitting the app will not make the bug reappear.
2. The KinectV2 compilation is consistent.
3.
4. 

**Expected behavior**

**Additional context**

Thanks for developing this software. I'm looking forward to trying to it control power up / down of Museum interactives.

**Comment by benkuper** [comment]
Hello and thank you,
few things :
- user feedback and issues are to be posted on Discord, not on github (reserved for code stuff)
- do not mention me directly as this is a collaborative project so anyone can help and get involved
- kinect2 is not officially sold and supported by Microsoft anymore, and was not made for mac by design (because of Microsoft), so there won't be any update nor support for MacOS in the Kinect module

have a great day :)
