### ISSUE TITLE
"go to preset" interpolation dosnt work on presets with a 0 value

### ISSUE THREAD

**Issue by nimitch** [benkuper/Chataigne#52]
have worked around by always using non zero presets 
this is the case on all mac os builds , will test same on rasberry pi and windows

**Comment by benkuper** [comment]
yes thank you for the feedback, it is a known bug that will be fixed soon. it actually is not because of zero values but because of "non overridden" parameters. when creating a preset, if you want to be sure that all values are taken into account, just modify them at least once so their label become bold, which means they have been overriden. then you can put whatever value you want and they will be working in go to preset.

**Comment by benkuper** [comment]
this will be fixed in 1.6.13b9
