### ISSUE TITLE
Mistreat of OSC address in Module Router

### ISSUE THREAD

**Issue by siteswapjuggler** [benkuper/Chataigne#62]
**Describe the bug**
OSC adresses are allowed with spaces in module router.

**To Reproduce**
1. create a custom variable and a OSC value 
2. create a module router linking the custom variable and the OSC value
3. set an OSC address with a space in it like "/address  M1" 

**Expected behavior**
I don't remeber osc adress to allow space, in contrary it could be nice to treat thos extra as string arguments even if it seems odd.

**Environment**
 - OS: Mac OS 10.13

**Comment by benkuper** [comment]
That's definitely not the philosophy of Chataigne, spaces have just been a quick and dirty way for max/msp style language to deal with multiple arguments, but considering that the whole software has a proper way of managing multiple arguments, "supporting" spaces as multiple arguments here would just bring confusion and make the workflow less consistent. 

You're right on the fact that spaces are not allowed in address space, but some softwares are still doing it (MadMapper has no address sanitizer in its automatic control addresses, maybe it changed since) and I chose to be compatible with thoses and rely on good practice from users. I could show a warning if there is a space though, which would at least show that there is something to fix, but considering spaces as argument separator is not a good practice IMHO.

Thanks for the feedback though :)
